version: '3'
services:
    database:
        container_name: database
        image: postgis/postgis:13-master
        # Required when running on platform other than amd64, like Apple M1/M2:
        # platform: linux/amd64
        volumes:
            - ./data/database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'

    cache:
        container_name: cache
        image: redis:7

    directus:
        container_name: directus
        image: directus/directus:10.10
        ports:
            - 8054:8055
        volumes:
            - ./my_uploads:/directus/uploads
            - ./my_extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            KEY: '255d861b-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '6116487b-b5b5-52c2-cda1-c8022c45e263'

            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'

            CACHE_ENABLED: false
            CACHE_STORE: 'redis'
            REDIS: 'redis://cache:6379'

            ADMIN_EMAIL: 'kontakt@abteilung.ch'
            ADMIN_PASSWORD: '5>-5tPX~dZc5'

            EMAIL_FROM: 'info@flohmarktkanzlei.ch'
            EMAIL_TRANSPORT: 'smtp'
            EMAIL_SMTP_HOST: 'smtp.mailersend.net'
            EMAIL_SMTP_PORT: '587'
            EMAIL_SMTP_USER: 'MS_wi2pYK@trial-neqvygm16pwg0p7w.mlsender.net'
            EMAIL_SMTP_PASSWORD: 'ZKyYZxirpKpBnTSQ'

            # Make sure to set this in production
            # (see https://docs.directus.io/self-hosted/config-options#general)
            PUBLIC_URL: 'https://flohmi-cms.kommando.info'
            CORS_ENABLED: true

        # Environment variables can also be defined in a file (for example `.env`):
        # env_file:
        #     - .env
volumes:
    my_uploads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/uploads
    my_extensions:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/extensions
