version: '3'
services:
    traefik:
        image: traefik:v2.5
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --entrypoints.web.address=:88
        ports:
            - '88:80'
            - '8089:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.api.rule=Host(`traefik.local`)'
            - 'traefik.http.routers.api.service=api@internal'
            - 'traefik.http.services.api.loadbalancer.server.port=8080'

    database:
        container_name: database
        image: postgis/postgis:13-master
        ports:
            - '5435:5432'
        volumes:
            - ./data/database:/var/lib/postgresql/data
        environment:
            TZ: ${TZ}
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'

    cache:
        container_name: cache
        image: redis:6

    directus:
        image: directus/directus:10.11.1
        volumes:
            - ./my_uploads:/directus/uploads
            - ./my_extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            TZ: ${TZ}
            KEY: '255d861b-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '6116487b-b5b5-52c2-cda1-c8022c45e263'
            WEBSOCKETS_ENABLED: 'true'
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}
            EMAIL_FROM: ${EMAIL_FROM}
            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'
            CACHE_ENABLED: 'true'
            CACHE_AUTO_PURGE: 'true'
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASS}
            PUBLIC_URL: https://${PUBLIC_URL}
            CORS_ENABLED: 'true'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.directus.rule=Host(`${PUBLIC_URL}`)'
            - 'traefik.http.services.directus.loadbalancer.server.port=8055'

    directus_replica:
        image: directus/directus:10.11.1
        volumes:
            - ./my_uploads:/directus/uploads
            - ./my_extensions:/directus/extensions
        environment:
            TZ: ${TZ}
            KEY: '255d861b-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '6116487b-b5b5-52c2-cda1-c8022c45e263'
            WEBSOCKETS_ENABLED: 'true'
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}
            EMAIL_FROM: ${EMAIL_FROM}
            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'
            CACHE_ENABLED: 'true'
            CACHE_AUTO_PURGE: 'true'
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASS}
            PUBLIC_URL: https://${PUBLIC_URL}
            CORS_ENABLED: 'true'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.directus.rule=Host(`${PUBLIC_URL}`)'
            - 'traefik.http.services.directus.loadbalancer.server.port=8055'

volumes:
    my_uploads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/uploads
    my_extensions:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/extensions
