version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
        restart: always

    database:
        container_name: database
        image: postgis/postgis:13-master
        ports:
            - '5435:5432'
        volumes:
            - ./data/database:/var/lib/postgresql/data
        environment:
            TZ: ${TZ}
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'

    cache:
        container_name: cache
        image: redis:6

    directus:
        ports:
            - '8055:8055'
        container_name: directus-master
        image: directus/directus:10.11.1
        volumes:
            - ./my_uploads:/directus/uploads
            - ./my_extensions:/directus/extensions
        depends_on:
            - cache
            - database
        environment:
            TZ: ${TZ}
            KEY: '861255db-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '6487b611-b5b5-52c2-cda1-c8022c45e263'
            WEBSOCKETS_ENABLED: 'true'
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}
            EMAIL_FROM: ${EMAIL_FROM}
            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'
            CACHE_ENABLED: 'true'
            CACHE_AUTO_PURGE: 'true'
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASS}
            PUBLIC_URL: https://${PUBLIC_URL}
            CORS_ENABLED: 'true'

    directus_replica:
        ports:
            - '8056:8055'
        container_name: directus-replica
        image: directus/directus:10.11.1
        volumes:
            - ./my_uploads:/directus/uploads
            - ./my_extensions:/directus/extensions
        environment:
            TZ: ${TZ}
            KEY: 'd861b255-5996-5ea1-9aa3-922530ec40b1'
            SECRET: '16487b61-b5b5-52c2-cda1-c8022c45e263'
            WEBSOCKETS_ENABLED: 'true'
            EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
            EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
            EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
            EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
            EMAIL_SMTP_IGNORE_TLS: ${EMAIL_SMTP_IGNORE_TLS}
            EMAIL_VERIFY_SETUP: ${EMAIL_VERIFY_SETUP}
            EMAIL_SMTP_POOL: ${EMAIL_SMTP_POOL}
            EMAIL_FROM: ${EMAIL_FROM}
            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'
            CACHE_ENABLED: 'true'
            CACHE_AUTO_PURGE: 'true'
            CACHE_TTL: '15m'
            CACHE_STORE: 'redis'
            ASSETS_CACHE_TTL: '300d'
            REDIS: 'redis://cache:6379'
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASS}
            PUBLIC_URL: https://${PUBLIC_URL}
            CORS_ENABLED: 'true'

volumes:
    my_uploads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/uploads
    my_extensions:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/extensions
