entryPoints:
    web:
        address: '81:80'
    websecure:
        address: ':443'
    traefik:
        address: ':8080'

api:
    dashboard: true

providers:
    docker:
        endpoint: 'unix:///var/run/docker.sock'
        exposedByDefault: false
